In [2]:
import numpy as np

In [4]:
b = np.array([1, 2])
b


array([1, 2])

In [6]:
b = np.reshape(b, (2, 1))
b

array([[1],
       [2]])

In [7]:
np.ones((2, 3)) + np.ones(3)

array([[2., 2., 2.],
       [2., 2., 2.]])

In [13]:
np.zeros((3, 1)) + np.zeros((1, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
x = np.arange(100).reshape(10, 10)
y = np.arange(10).reshape(10,1)
y

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [22]:
x = np.array([5, 2, 3, 1])
x

array([5, 2, 3, 1])

In [23]:
np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])

array([[1, 0, 1],
       [2, 0, 2],
       [3, 0, 3],
       [4, 4, 4]])

In [24]:
def task_2(A):
    i =0
    result=1
    none = True
    while (i<len(A) and i<len(A[i])):
        if A[i][i]!=0:
            result *= A[i][i]
            none = False
            i+=1
        else:
            i+=1
        return result if not none else None

print(task_2(np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])))

1


In [33]:
X = np.arange(32).reshape(8, 4)
X[7][3]


31

In [34]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])